### ISSUE TITLE
Getting proxy error on subdomain

### ISSUE THREAD

**Issue by adnankhanakib** [waelmas/frameless-bitb#10]
Hello, I've noticed that I am getting proxy error only when I use sub-domain. When I try to access main domain it shows landing page perfectly.

![image](https://github.com/waelmas/frameless-bitb/assets/39073336/1c3c64e5-a9dd-4163-83fc-c93e7782fef3)

**Comment by waelmas** [comment]
Hey again,

Did you check that Evilginx on its own is working properly as discussed in https://github.com/waelmas/frameless-bitb/issues/9 ?

Since the homepage is working, this is 99% an issue with Evilginx being unreachable on port 8443.

**Comment by waelmas** [comment]
Seems like this issue is related to Evilginx setup, closing it for now but if this is not the case, please open a new issue. Just please make sure the Evilginx setup alone is working properly first and make sure to attach all relevant information.
